### ISSUE TITLE
Cursor jumping down after formatting

### ISSUE THREAD

**Issue by mariojackson** [tonycoco/PrettySwift#2]
I activated a shortcut to format the current file when pressing `CMD + S`. However, when I use it, the cursor jumps to the end of the file, requiring me to scroll back to my original editing position. 

Is there a way to keep the cursor at the editing position after formatting?

**Comment by tonycoco** [comment]
I will look into this. Are you on the latest version of Xcode?

**Comment by mariojackson** [comment]
Thanks! Yes, I'm using Xcode version 15.4. 

![CleanShot 2024-05-31 at 13 56 57](https://github.com/tonycoco/PrettySwift/assets/57389555/48b5b04e-36e9-4f44-8db0-fda8acafbcb2)

**Comment by tonycoco** [comment]
Fixed with version 1.2. Releasing now.
