### ISSUE TITLE
xcode source editor doesnt appear in privacy security

### ISSUE THREAD

**Issue by AlfinIndrawan** [tonycoco/PrettySwift#3]
i installing your apps but when i tried to enable the system settings. i cant find any of xcode source editor. is the access deleted by the new macos?

Macos 15, M2 macbook is my device.

**Comment by tonycoco** [comment]
Have you updated Xcode and launched the installer application?

**Comment by AlfinIndrawan** [comment]
<img width="673" alt="SCR-20241110-qdlp" src="https://github.com/user-attachments/assets/cf8b9e46-efb5-44c4-bb8b-e7f939f6bad6">

my xcode is 16.1 and macos 15.1. this is quite old issue and still hasnt been fixed for me in the settings. and yes i tried to add in developer tools but your app keep showing installation page "in system settings, enable the prettyswift xcode source extension".

**Comment by tonycoco** [comment]
Oh, in macOS 15.1 you need to open `System Settings.app`. Go to `General > Login Items & Extensions > Xcode Source Editor`, then toggle on `PrettySwift for Xcode`
